package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// HookEvent represents a structured event written by an agent hook.
type HookEvent struct {
	Event     string    `json:"event"`
	Tool      string    `json:"tool,omitempty"`
	Timestamp time.Time `json:"ts"`
	SessionID string    `json:"session_id"`
	Data      any       `json:"data,omitempty"`
}

// Installer auto-configures agent hooks for a session.
type Installer struct {
	OutputDir string
}

// NewInstaller creates a hook installer.
func NewInstaller(outputDir string) *Installer {
	return &Installer{OutputDir: outputDir}
}

// Install generates the hook script for a session and returns the JSONL
// output path that the watcher should monitor.
func (i *Installer) Install(sessionID, agent, hookDir string) (string, error) {
	outputPath := i.OutputPath(sessionID)
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", fmt.Errorf("create hook output dir: %w", err)
	}

	switch agent {
	case "claude":
		return outputPath, i.installClaudeHooks(sessionID, hookDir, outputPath)
	case "codex":
		return outputPath, nil // codex uses pipe-pane output parsing
	default:
		return outputPath, nil // screen_only agents don't need hook scripts
	}
}

// OutputPath returns the JSONL file path for a session's hook events.
func (i *Installer) OutputPath(sessionID string) string {
	return filepath.Join(i.OutputDir, fmt.Sprintf("atrs-hooks-%s.jsonl", sessionID))
}

// Cleanup removes hook artifacts for a session.
func (i *Installer) Cleanup(sessionID string) error {
	return os.Remove(i.OutputPath(sessionID))
}

func (i *Installer) installClaudeHooks(sessionID, hookDir, outputPath string) error {
	// Generate a hook script that Claude Code will invoke
	script := fmt.Sprintf(`#!/bin/sh
# Auto-generated by atrs for session %s
# Writes structured hook events to %s
EVENT_TYPE="${CLAUDE_HOOK_EVENT_TYPE:-unknown}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
printf '{"event":"%%s","tool":"%%s","ts":"%%s","session_id":"%s"}\n' \
  "$EVENT_TYPE" "$TOOL_NAME" "$(date -u +%%FT%%TZ)" >> "%s"
`, sessionID, outputPath, sessionID, outputPath)

	hookScriptPath := filepath.Join(hookDir, "hooks", fmt.Sprintf("atrs-%s.sh", sessionID))
	if err := os.MkdirAll(filepath.Dir(hookScriptPath), 0o755); err != nil {
		return fmt.Errorf("create hook script dir: %w", err)
	}
	if err := os.WriteFile(hookScriptPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	return nil
}

// ParseHookEvent parses a single line from a hook JSONL file.
func ParseHookEvent(line []byte) (HookEvent, error) {
	var event HookEvent
	if err := json.Unmarshal(line, &event); err != nil {
		return HookEvent{}, err
	}
	return event, nil
}
