package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// HookEvent represents a structured event written by an agent hook.
type HookEvent struct {
	Event     string    `json:"event"`
	Tool      string    `json:"tool,omitempty"`
	Timestamp time.Time `json:"ts"`
	SessionID string    `json:"session_id"`
	Data      any       `json:"data,omitempty"`
}

// genericHookName is the single, session-agnostic Claude hook script arcmux
// installs. It replaces the old per-session arcmux-<sessionID>.sh files: the
// per-session output path is now derived at runtime from environment
// (ARCMUX_SESSION_ID + ARCMUX_HOOK_OUTPUT_DIR) supplied to the spawned agent,
// so one script serves every session and re-install is idempotent.
const genericHookName = "arcmux-session-hook.sh"

// genericHookScript is the fixed content of the generic hook. It no-ops unless
// an arcmux-spawned session provided the env below, so the single script is
// safe to install once and reference globally. The JSONL filename it derives
// (arcmux-hooks-<id>.jsonl under ARCMUX_HOOK_OUTPUT_DIR) is byte-identical to
// Installer.OutputPath, so the watcher keeps finding each session's file.
//
// It understands both hook payload dialects:
//   - Claude Code: {"hook_event_name":"PreToolUse","tool_name":"Bash",...}
//   - Grok Build:  {"hookEventName":"pre_tool_use","toolName":"run_terminal_command",...}
//
// so the SAME script serves claude sessions (registered via Claude settings)
// and grok sessions (registered via the drop-in ~/.grok/hooks/arcmux-session.json).
const genericHookScript = `#!/bin/sh
# Auto-generated by arcmux — generic session-aware hook (idempotent).
# Two jobs, both no-ops unless an arcmux-spawned session set ARCMUX_SESSION_ID:
#   1) append the raw event to a per-session JSONL audit trail (the Watcher
#      tails this — preserved behavior).
#   2) mutate the per-session state doc via "arcmux hook" (the cached data the
#      hooks judge reads), translating the agent's event type to a canonical event.
# Claude Code hooks deliver {"hook_event_name","tool_name"} on stdin; Grok Build
# delivers {"hookEventName","toolName"} (snake_case event values). The CLAUDE_*
# env vars are honored only as a legacy fallback. Safe to install once globally.
[ -n "$ARCMUX_SESSION_ID" ] || exit 0

payload=$(cat 2>/dev/null || printf '')
EVENT_TYPE="${CLAUDE_HOOK_EVENT_TYPE:-}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"

if command -v python3 >/dev/null 2>&1; then
  parsed=$(printf '%s' "$payload" | python3 -c 'import json,sys
raw=sys.stdin.read()
e="";t="";goal="";verification="";path=""
def first_text(d, keys):
    for key in keys:
        value=d.get(key)
        if isinstance(value,str) and value.strip():
            return " ".join(value.split())
    return ""
try:
    d=json.loads(raw) if raw.strip() else {}
    if isinstance(d,dict):
        e=d.get("hook_event_name") or d.get("hookEventName") or ""
        t=d.get("tool_name") or d.get("toolName") or ""
        goal=first_text(d, ("arcmux_goal","goal","objective","prompt","message","text"))
        verification=first_text(d, ("arcmux_success_verification","success_verification","verification","success_check"))
        path=first_text(d, ("arcmux_path","path","plan","approach"))
except Exception:
    pass
print(e);print(t);print(goal);print(verification);print(path)' 2>/dev/null)
  je=$(printf '%s\n' "$parsed" | sed -n '1p')
  jt=$(printf '%s\n' "$parsed" | sed -n '2p')
  jgoal=$(printf '%s\n' "$parsed" | sed -n '3p')
  jverification=$(printf '%s\n' "$parsed" | sed -n '4p')
  jpath=$(printf '%s\n' "$parsed" | sed -n '5p')
else
  je=$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$je" ] || je=$(printf '%s' "$payload" | sed -n 's/.*"hookEventName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jt=$(printf '%s' "$payload" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$jt" ] || jt=$(printf '%s' "$payload" | sed -n 's/.*"toolName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jgoal=""
  jverification=""
  jpath=""
fi
[ -n "$je" ] && EVENT_TYPE="$je"
[ -n "$jt" ] && TOOL_NAME="$jt"
[ -n "$EVENT_TYPE" ] || EVENT_TYPE=unknown

# 1) JSONL audit (only when an output dir was provided).
if [ -n "$ARCMUX_HOOK_OUTPUT_DIR" ]; then
  out="$ARCMUX_HOOK_OUTPUT_DIR/arcmux-hooks-$ARCMUX_SESSION_ID.jsonl"
  mkdir -p "$ARCMUX_HOOK_OUTPUT_DIR" 2>/dev/null
  printf '{"event":"%s","tool":"%s","ts":"%s","session_id":"%s"}\n' \
    "$EVENT_TYPE" "$TOOL_NAME" "$(date -u +%FT%TZ)" "$ARCMUX_SESSION_ID" >> "$out"
fi

# 2) Canonical state mutation via the arcmux binary. Claude event values are
# PascalCase; grok's are snake_case — both map to the same canonical events.
case "$EVENT_TYPE" in
  UserPromptSubmit|user_prompt_submit) CANON=prompt_submit; TOOL_NAME="" ;;
  PreToolUse|pre_tool_use)             CANON=tool_start ;;
  PostToolUse|post_tool_use)           CANON=tool_end ;;
  Stop|stop)                           CANON=turn_end; TOOL_NAME="" ;;
  *)                                   CANON=notification ;;
esac
ARCMUX_BIN="${ARCMUX_BIN:-arcmux}"
set -- hook --agent "${ARCMUX_HOOK_AGENT:-claude}" --event "$CANON" --tool "$TOOL_NAME"
[ -n "$jgoal" ] && set -- "$@" --goal "$jgoal"
[ -n "$jverification" ] && set -- "$@" --verification "$jverification"
[ -n "$jpath" ] && set -- "$@" --path "$jpath"
if [ -n "$jgoal$jverification$jpath" ]; then
  set -- "$@" --contract-source "$EVENT_TYPE"
fi
"$ARCMUX_BIN" "$@" >/dev/null 2>&1 || true

if [ "$CANON" = "prompt_submit" ] && command -v python3 >/dev/null 2>&1; then
  python3 - <<'PY' 2>/dev/null || true
import json
msg = (
    "Arcmux turn contract: keep the current goal, success verification, and "
    "path concrete. Consolidate path updates instead of appending a log; "
    "treat user or agent steers as edits to one of those three fields."
)
print(json.dumps({
    "systemMessage": msg,
    "hookSpecificOutput": {
        "hookEventName": "UserPromptSubmit",
        "additionalContext": msg,
    },
}))
PY
fi
`

// Installer auto-configures the generic agent hook for sessions.
type Installer struct {
	OutputDir string
}

// NewInstaller creates a hook installer.
func NewInstaller(outputDir string) *Installer {
	return &Installer{OutputDir: outputDir}
}

// Install ensures the hook artifacts for the profile's hook type exist and
// returns the JSONL output path the watcher should monitor for this session.
// The scripts are session-agnostic and written idempotently; only the returned
// output path is session-specific. Keyed by the profile's HookType — not the
// agent name — so custom/config-defined profiles route correctly.
func (i *Installer) Install(sessionID, hookType, hookDir string) (string, error) {
	outputPath := i.OutputPath(sessionID)
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", fmt.Errorf("create hook output dir: %w", err)
	}

	switch hookType {
	case "claude_hooks":
		return outputPath, i.installGenericHook(hookDir)
	case "grok_hooks":
		// Grok loads drop-in JSON hook files from <hookDir>/hooks (always
		// trusted), so install the generic script there plus the registration
		// file that points grok's lifecycle events at it.
		return outputPath, i.EnsureGrokHook(hookDir)
	case "codex_output":
		return outputPath, nil // codex bridge script is materialized at daemon startup
	default:
		return outputPath, nil // screen_only / structured_output agents don't need hook scripts
	}
}

// OutputPath returns the JSONL file path for a session's hook events.
func (i *Installer) OutputPath(sessionID string) string {
	return filepath.Join(i.OutputDir, fmt.Sprintf("arcmux-hooks-%s.jsonl", sessionID))
}

// GenericHookPath returns the absolute path of the single generic hook script
// inside hookDir.
func GenericHookPath(hookDir string) string {
	return filepath.Join(hookDir, "hooks", genericHookName)
}

// EnsureGenericHook writes the shared, session-aware Claude hook without
// requiring a concrete session. Daemon startup uses this so the global hook is
// present immediately after deploy/restart; per-session Install still returns
// each session's JSONL path and remains the watcher contract.
func (i *Installer) EnsureGenericHook(hookDir string) error {
	return i.installGenericHook(hookDir)
}

// Cleanup removes the per-session JSONL output file. It deliberately does NOT
// remove the generic hook script: that script is shared across every session,
// so tearing down one session must not delete it. Either artifact may be
// absent (e.g. codex sessions have no JSONL yet).
func (i *Installer) Cleanup(sessionID string) error {
	if err := os.Remove(i.OutputPath(sessionID)); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// installGenericHook writes the single generic hook script idempotently.
// Re-writing identical content is skipped so concurrent/ repeated installs
// don't churn the file.
func (i *Installer) installGenericHook(hookDir string) error {
	// Defense in depth: a relative hookDir is almost certainly a bug upstream
	// (filepath.Join does not expand "~", and the daemon's cwd is not a
	// meaningful base for user-config paths).
	if !filepath.IsAbs(hookDir) {
		return fmt.Errorf("hook dir must be absolute, got %q (config or profile.HookDir was not resolved at load time)", hookDir)
	}

	path := GenericHookPath(hookDir)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create hook script dir: %w", err)
	}
	// Idempotent: if the file already holds the exact content, do nothing.
	if existing, err := os.ReadFile(path); err == nil && string(existing) == genericHookScript {
		return nil
	}
	if err := os.WriteFile(path, []byte(genericHookScript), 0o755); err != nil {
		return fmt.Errorf("write generic hook script: %w", err)
	}
	return nil
}

// CleanupLegacyScripts removes the per-session hook scripts left behind by the
// old generator (arcmux-s-*.sh under hookDir/hooks). It is the coded migration
// that sweeps the stray files instead of a manual one-off rm: idempotent
// (zero matches is fine), it never touches the generic hook, and it returns the
// number of scripts removed. Safe to call on every daemon startup.
func (i *Installer) CleanupLegacyScripts(hookDir string) (int, error) {
	if !filepath.IsAbs(hookDir) {
		return 0, fmt.Errorf("hook dir must be absolute, got %q", hookDir)
	}
	matches, err := filepath.Glob(filepath.Join(hookDir, "hooks", "arcmux-s-*.sh"))
	if err != nil {
		return 0, fmt.Errorf("glob legacy hook scripts: %w", err)
	}
	generic := GenericHookPath(hookDir)
	removed := 0
	var firstErr error
	for _, m := range matches {
		if m == generic {
			continue // defensive: the glob can't match the generic name, but be explicit
		}
		if err := os.Remove(m); err != nil && !os.IsNotExist(err) {
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		removed++
	}
	return removed, firstErr
}

// ParseHookEvent parses a single line from a hook JSONL file.
func ParseHookEvent(line []byte) (HookEvent, error) {
	var event HookEvent
	if err := json.Unmarshal(line, &event); err != nil {
		return HookEvent{}, err
	}
	return event, nil
}
