package hooks

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// HookEvent represents a structured event written by an agent hook.
type HookEvent struct {
	Event     string    `json:"event"`
	Tool      string    `json:"tool,omitempty"`
	Timestamp time.Time `json:"ts"`
	SessionID string    `json:"session_id"`
	Data      any       `json:"data,omitempty"`
}

// Installer auto-configures agent hooks for a session.
type Installer struct {
	OutputDir string

	mu      sync.Mutex
	scripts map[string]string // sessionID -> absolute path of generated hook script
}

// NewInstaller creates a hook installer.
func NewInstaller(outputDir string) *Installer {
	return &Installer{
		OutputDir: outputDir,
		scripts:   make(map[string]string),
	}
}

// Install generates the hook script for a session and returns the JSONL
// output path that the watcher should monitor.
func (i *Installer) Install(sessionID, agent, hookDir string) (string, error) {
	outputPath := i.OutputPath(sessionID)
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return "", fmt.Errorf("create hook output dir: %w", err)
	}

	switch agent {
	case "claude":
		return outputPath, i.installClaudeHooks(sessionID, hookDir, outputPath)
	case "codex":
		return outputPath, nil // codex uses pipe-pane output parsing
	default:
		return outputPath, nil // screen_only agents don't need hook scripts
	}
}

// OutputPath returns the JSONL file path for a session's hook events.
func (i *Installer) OutputPath(sessionID string) string {
	return filepath.Join(i.OutputDir, fmt.Sprintf("arcmux-hooks-%s.jsonl", sessionID))
}

// Cleanup removes hook artifacts for a session: the JSONL output file
// and, if one was installed, the per-session hook script written by
// installClaudeHooks. Either may legitimately be absent (e.g. for codex
// sessions that have no script).
func (i *Installer) Cleanup(sessionID string) error {
	var firstErr error
	if err := os.Remove(i.OutputPath(sessionID)); err != nil && !os.IsNotExist(err) {
		firstErr = err
	}

	i.mu.Lock()
	scriptPath, ok := i.scripts[sessionID]
	delete(i.scripts, sessionID)
	i.mu.Unlock()

	if ok {
		if err := os.Remove(scriptPath); err != nil && !os.IsNotExist(err) && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

func (i *Installer) installClaudeHooks(sessionID, hookDir, outputPath string) error {
	// Defense in depth: a relative hookDir is almost certainly a bug
	// upstream (filepath.Join does not expand "~", and the daemon's cwd
	// is not a meaningful base for user-config paths). Reject loud
	// instead of silently creating a "~/.claude/hooks/..." tree under
	// the caller's working directory.
	if !filepath.IsAbs(hookDir) {
		return fmt.Errorf("hook dir must be absolute, got %q (config or profile.HookDir was not resolved at load time)", hookDir)
	}

	// Generate a hook script that Claude Code will invoke
	script := fmt.Sprintf(`#!/bin/sh
# Auto-generated by arcmux for session %s
# Writes structured hook events to %s
EVENT_TYPE="${CLAUDE_HOOK_EVENT_TYPE:-unknown}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
printf '{"event":"%%s","tool":"%%s","ts":"%%s","session_id":"%s"}\n' \
  "$EVENT_TYPE" "$TOOL_NAME" "$(date -u +%%FT%%TZ)" >> "%s"
`, sessionID, outputPath, sessionID, outputPath)

	hookScriptPath := filepath.Join(hookDir, "hooks", fmt.Sprintf("arcmux-%s.sh", sessionID))
	if err := os.MkdirAll(filepath.Dir(hookScriptPath), 0o755); err != nil {
		return fmt.Errorf("create hook script dir: %w", err)
	}
	if err := os.WriteFile(hookScriptPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}

	i.mu.Lock()
	i.scripts[sessionID] = hookScriptPath
	i.mu.Unlock()
	return nil
}

// ParseHookEvent parses a single line from a hook JSONL file.
func ParseHookEvent(line []byte) (HookEvent, error) {
	var event HookEvent
	if err := json.Unmarshal(line, &event); err != nil {
		return HookEvent{}, err
	}
	return event, nil
}
