#!/bin/sh
# Auto-generated by arcmux — unified session-aware hook (idempotent).
#
# ONE script for every hook-backed agent class (claude, codex, grok). It no-ops
# unless an arcmux-spawned session set ARCMUX_SESSION_ID, so it is safe to
# install once globally and have non-arcmux sessions fire it harmlessly.
#
# Jobs:
#   1) append the raw event to a per-session JSONL audit trail (the Watcher
#      tails this), when ARCMUX_HOOK_OUTPUT_DIR is set.
#   2) mutate the per-session state doc via `arcmux hook`, recording what the
#      session is doing — the THREE valued views (recording, not steering):
#        - goal:              latest gauged "Your ask:" (the current sub-task)
#        - last_user_message: the raw last user turn (Go truncates to 3 lines)
#        - vault_link:        where the conversation is saved in the vault
#   3) on turn_end, fire a background, best-effort summarizer (xAI grok) that
#      passes the kept conversation + the current overall goal to the model and
#      writes back a refreshed, continuously-evolving overall_goal — one
#      succinct line, or a checklist with prior gears checked off when the
#      conversation has split into separate themes.
#
# Input dialects, all understood by the same script:
#   - Claude Code: stdin {"hook_event_name":...,"tool_name":...,"prompt":...,
#     "transcript_path":...}; no argv.
#   - Grok Build:  stdin {"hookEventName":...,"toolName":...}; no argv.
#   - Codex:       native event as argv[1] (e.g. `... Stop`) + stdin
#     {"transcript_path":...,"turn_id":...}; legacy `notify` passes the JSON as
#     argv[1] instead of stdin.
[ -n "$ARCMUX_SESSION_ID" ] || exit 0

arg_event=""
payload=""
case "${1:-}" in
  \{*) payload="$1" ;;          # legacy codex notify: JSON in argv
  ?*)  arg_event="$1" ;;        # codex native event name
esac
[ -n "$payload" ] || payload=$(cat 2>/dev/null || printf '')

EVENT_TYPE="${CLAUDE_HOOK_EVENT_TYPE:-}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
USER_MSG=""
GOAL=""

if command -v python3 >/dev/null 2>&1; then
  parsed=$(printf '%s' "$payload" | python3 -c '
import base64, json, sys
from pathlib import Path

raw = sys.stdin.read()

def oneline(text, limit=600):
    return " ".join(str(text).split())[:limit]

def msg_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        out = []
        for it in content:
            if isinstance(it, dict) and isinstance(it.get("text"), str):
                out.append(it["text"])
        return "\n".join(out)
    return ""

# Normalize one transcript line (codex payload-wrapped or claude/grok flat) to
# (role, text, turn_id).
def normalize(item):
    if not isinstance(item, dict):
        return None
    inner = item.get("payload") if isinstance(item.get("payload"), dict) else None
    src = inner or (item.get("message") if isinstance(item.get("message"), dict) else item)
    if not isinstance(src, dict):
        return None
    if inner is not None and src.get("type") not in (None, "message"):
        return None
    role = src.get("role") or item.get("role")
    text = msg_text(src.get("content"))
    if not text:
        return None
    turn = None
    meta = (inner or {}).get("metadata")
    if isinstance(meta, dict):
        turn = meta.get("turn_id")
    return (role, text, turn)

def scan_transcript(path, want_turn):
    last_user = ""
    last_assistant = ""
    try:
        with Path(path).open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    item = json.loads(line)
                except Exception:
                    continue
                norm = normalize(item)
                if not norm:
                    continue
                role, text, turn = norm
                if want_turn and turn is not None and turn != want_turn:
                    continue
                if role == "user":
                    last_user = text
                elif role == "assistant":
                    last_assistant = text
    except Exception:
        return "", ""
    return last_user, last_assistant

def gauged_goal(assistant):
    # The agent restates intent as "Your ask: <paraphrase>" (AGENTS.md). That
    # line IS the LLM-gauged latest goal for the turn — scrape the last one.
    found = ""
    for line in assistant.splitlines():
        s = line.strip()
        if s.lower().startswith("your ask:"):
            found = oneline(s.split(":", 1)[1])
    return found

def keep_lines(text, n=3, limit=300):
    lines = []
    for line in str(text).split("\n"):
        if len(lines) >= n:
            break
        lines.append(line[:limit])
    out = "\n".join(lines)
    if len(str(text).split("\n")) > n:
        out += "\n…"
    return out

event = ""; tool = ""; notify_type = ""; user_msg = ""; goal = ""
try:
    d = json.loads(raw) if raw.strip() else {}
    if isinstance(d, dict):
        event = d.get("hook_event_name") or d.get("hookEventName") or ""
        tool = d.get("tool_name") or d.get("toolName") or ""
        notify_type = d.get("type") or ""
        # Direct fields first (claude/grok give the prompt on UserPromptSubmit).
        for key in ("arcmux_last_message", "prompt", "message", "text"):
            v = d.get(key)
            if isinstance(v, str) and v.strip():
                user_msg = v
                break
        goal = ""
        for key in ("arcmux_goal", "goal", "objective"):
            v = d.get(key)
            if isinstance(v, str) and v.strip():
                goal = oneline(v)
                break
        transcript = d.get("transcript_path")
        if isinstance(transcript, str) and transcript:
            turn_id = d.get("turn_id") if isinstance(d.get("turn_id"), str) else None
            t_user, t_assistant = scan_transcript(transcript, turn_id)
            if not user_msg and t_user:
                user_msg = t_user
            if not goal and t_assistant:
                goal = gauged_goal(t_assistant)
except Exception:
    pass

user_b64 = base64.b64encode(keep_lines(user_msg).encode("utf-8")).decode() if user_msg else ""
print(event)
print(tool)
print(notify_type)
print(user_b64)
print(goal)
' 2>/dev/null)
  je=$(printf '%s\n' "$parsed" | sed -n '1p')
  jt=$(printf '%s\n' "$parsed" | sed -n '2p')
  jnotify=$(printf '%s\n' "$parsed" | sed -n '3p')
  user_b64=$(printf '%s\n' "$parsed" | sed -n '4p')
  GOAL=$(printf '%s\n' "$parsed" | sed -n '5p')
  if [ -n "$user_b64" ]; then
    USER_MSG=$(printf '%s' "$user_b64" | python3 -c 'import base64,sys;sys.stdout.write(base64.b64decode(sys.stdin.read()).decode("utf-8","replace"))' 2>/dev/null)
  fi
else
  je=$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$je" ] || je=$(printf '%s' "$payload" | sed -n 's/.*"hookEventName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jt=$(printf '%s' "$payload" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$jt" ] || jt=$(printf '%s' "$payload" | sed -n 's/.*"toolName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jnotify=$(printf '%s' "$payload" | sed -n 's/.*"type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
fi

# Resolve the native event: codex argv hint, else JSON event, else notify type.
[ -n "$arg_event" ] && EVENT_TYPE="$arg_event"
[ -n "$je" ] && [ -z "$arg_event" ] && EVENT_TYPE="$je"
[ -n "$EVENT_TYPE" ] || EVENT_TYPE="$jnotify"
[ -n "$jt" ] && TOOL_NAME="$jt"
[ -n "$EVENT_TYPE" ] || EVENT_TYPE=unknown

# 1) JSONL audit (only when an output dir was provided).
if [ -n "$ARCMUX_HOOK_OUTPUT_DIR" ]; then
  out="$ARCMUX_HOOK_OUTPUT_DIR/arcmux-hooks-$ARCMUX_SESSION_ID.jsonl"
  mkdir -p "$ARCMUX_HOOK_OUTPUT_DIR" 2>/dev/null
  printf '{"event":"%s","tool":"%s","ts":"%s","session_id":"%s"}\n' \
    "$EVENT_TYPE" "$TOOL_NAME" "$(date -u +%FT%TZ)" "$ARCMUX_SESSION_ID" >> "$out"
fi

# 2) Map the native event (claude PascalCase, grok snake_case, codex names) to a
# canonical event. Unmapped events are dropped (exit 0), not recorded as noise.
case "$EVENT_TYPE" in
  UserPromptSubmit|user_prompt_submit)            CANON=prompt_submit; TOOL_NAME="" ;;
  PreToolUse|pre_tool_use)                         CANON=tool_start ;;
  PostToolUse|post_tool_use)                       CANON=tool_end ;;
  Stop|stop|SubagentStop|agent-turn-complete)      CANON=turn_end; TOOL_NAME="" ;;
  Notification|notification|approval-requested|PermissionRequest) CANON=notification ;;
  SessionStart|SubagentStart|PreCompact|PostCompact)              CANON=notification ;;
  unknown)                                         CANON=notification ;;
  *)                                               exit 0 ;;
esac

# 3) Best-effort vault link: only on turn_end, find the history log under
# ~/agents/histories whose frontmatter cwd matches this session (newest mtime).
VAULT_LINK=""
if [ "$CANON" = "turn_end" ] && [ -n "$ARCMUX_SESSION_CWD" ] && command -v python3 >/dev/null 2>&1; then
  VAULT_LINK=$(ARCMUX_SESSION_CWD="$ARCMUX_SESSION_CWD" python3 -c '
import os, glob
from pathlib import Path
cwd = os.environ.get("ARCMUX_SESSION_CWD", "")
host = os.uname().nodename.split(".")[0]
root = os.path.expanduser("~/agents/histories")
best = ""; best_mtime = -1.0
for f in glob.glob(os.path.join(root, "*.md")):
    try:
        head = Path(f).read_text(encoding="utf-8", errors="ignore")[:1500]
    except Exception:
        continue
    fm_cwd = ""; fm_host = ""
    for line in head.splitlines():
        s = line.strip()
        if s.startswith("cwd:"):
            fm_cwd = s.split(":", 1)[1].strip()
        elif s.startswith("host:"):
            fm_host = s.split(":", 1)[1].strip()
        elif s == "---" and (fm_cwd or fm_host):
            break
    if not fm_cwd or fm_cwd != cwd:
        continue
    if fm_host and host and fm_host != host:
        continue
    try:
        m = os.path.getmtime(f)
    except OSError:
        continue
    if m > best_mtime:
        best_mtime = m; best = f
print(best)
' 2>/dev/null)
fi

# 4) Mutate the state doc. arcmux hook reads session/agent/state-dir from env by
# default; pass recording fields only when present so empty values never clobber.
ARCMUX_BIN="${ARCMUX_BIN:-arcmux}"
set -- hook --agent "${ARCMUX_HOOK_AGENT:-claude}" --event "$CANON" --tool "$TOOL_NAME"
[ -n "$GOAL" ] && set -- "$@" --goal "$GOAL"
[ -n "$USER_MSG" ] && set -- "$@" --last-message "$USER_MSG"
[ -n "$VAULT_LINK" ] && set -- "$@" --vault-link "$VAULT_LINK"
if [ -n "$GOAL$USER_MSG$VAULT_LINK" ]; then
  set -- "$@" --contract-source "$EVENT_TYPE"
fi
"$ARCMUX_BIN" "$@" >/dev/null 2>&1 || true

# 5) Continuously-evolving overall_goal: on turn_end, refresh it in the
# background (best-effort, debounced) by passing the kept conversation + the
# current overall goal to xAI grok. Never blocks the turn; if grok is missing or
# fails, overall_goal simply keeps its prior value.
arcmux_refresh_overall() {
  [ -n "$VAULT_LINK" ] && [ -f "$VAULT_LINK" ] || return 0
  goal_bin="${ARCMUX_GOAL_BIN:-grok}"
  command -v "$goal_bin" >/dev/null 2>&1 || return 0
  [ -n "$ARCMUX_SESSION_STATE_DIR" ] || return 0

  # Debounce: at most one refresh per session at a time (mkdir is atomic).
  lock="$ARCMUX_SESSION_STATE_DIR/.overall-goal-${ARCMUX_SESSION_ID}.lock"
  mkdir "$lock" 2>/dev/null || return 0
  trap 'rmdir "$lock" 2>/dev/null' EXIT

  state="$ARCMUX_SESSION_STATE_DIR/$ARCMUX_SESSION_ID.json"
  current=$(python3 -c 'import json,sys
try:
    d=json.load(open(sys.argv[1]))
    print(((d.get("turn_contract") or {}).get("overall_goal") or ""))
except Exception:
    pass' "$state" 2>/dev/null)

  convo=$(tail -c 12000 "$VAULT_LINK" 2>/dev/null)
  [ -n "$convo" ] || return 0

  pf=$(mktemp 2>/dev/null) || return 0
  {
    printf '%s\n' "You maintain a running OVERALL GOAL for an agent work session: what the user is ultimately trying to achieve across the whole conversation."
    printf '%s\n\n' "It evolves with the conversation."
    printf '%s\n%s\n\n' "Current overall goal:" "${current:-(none yet)}"
    printf '%s\n%s\n\n' "Conversation so far (newest last):" "$convo"
    printf '%s\n' "Return the UPDATED overall goal. Normally ONE succinct line. If the conversation has clearly shifted into multiple separate themes, return a short markdown checklist instead: completed or abandoned earlier goals as '- [x] ...' and the active one(s) as '- [ ] ...'. Output ONLY the goal text — no preamble, no quotes, no explanation."
  } > "$pf"

  # Bound the call and detach stdin: an unauthenticated/slow grok must degrade
  # (overall_goal keeps its prior value) rather than hang as a lingering process
  # or block on an interactive auth prompt.
  if command -v timeout >/dev/null 2>&1; then
    new=$(timeout "${ARCMUX_GOAL_TIMEOUT:-90}" "$goal_bin" --no-alt-screen --disable-web-search -m "${ARCMUX_GOAL_MODEL:-grok-4.3}" --prompt-file "$pf" </dev/null 2>/dev/null)
  else
    new=$("$goal_bin" --no-alt-screen --disable-web-search -m "${ARCMUX_GOAL_MODEL:-grok-4.3}" --prompt-file "$pf" </dev/null 2>/dev/null)
  fi
  rm -f "$pf"
  # Trim leading/trailing blank lines.
  new=$(printf '%s\n' "$new" | sed -e '/./,$!d' | sed -e ':a' -e '/^\n*$/{$d;N;ba}' 2>/dev/null)
  [ -n "$new" ] || return 0
  # Contract-only write (no --event): refreshes overall_goal without perturbing
  # the event stream or counters.
  "$ARCMUX_BIN" hook --overall-goal "$new" \
    --overall-goal-provenance hook.overall_goal_summarizer.v1 >/dev/null 2>&1 || true
}
if [ "$CANON" = "turn_end" ]; then
  ( arcmux_refresh_overall & ) >/dev/null 2>&1
fi
exit 0
