#!/bin/sh
# Auto-generated by arcmux — unified session-aware hook (idempotent).
#
# ONE script for every hook-backed agent class (claude, codex, grok). It no-ops
# unless an arcmux-spawned session set ARCMUX_SESSION_ID, so it is safe to
# install once globally and have non-arcmux sessions fire it harmlessly.
#
# Jobs:
#   1) append the raw event to a per-session JSONL audit trail (the Watcher
#      tails this), when ARCMUX_HOOK_OUTPUT_DIR is set.
#   2) mutate the per-session state doc via `arcmux hook`, recording what the
#      session is doing — the THREE valued views (recording, not steering):
#        - goal:              latest gauged "Your ask:" (the current sub-task)
#        - last_user_message: the raw last user turn (Go truncates to 3 lines)
#
# The daemon owner observes turn_end state and performs overall-goal inference.
# The pane hook deliberately has no command that can stamp trusted provenance.
#
# Input dialects, all understood by the same script:
#   - Claude Code: stdin {"hook_event_name":...,"tool_name":...,"prompt":...,
#     "transcript_path":...}; no argv.
#   - Grok Build:  stdin {"hookEventName":...,"toolName":...}; no argv.
#   - Codex:       native event as argv[1] (e.g. `... Stop`) + stdin
#     {"transcript_path":...,"turn_id":...}; legacy `notify` passes the JSON as
#     argv[1] instead of stdin.
[ -n "$ARCMUX_SESSION_ID" ] || exit 0

arg_event=""
payload=""
case "${1:-}" in
  \{*) payload="$1" ;;          # legacy codex notify: JSON in argv
  ?*)  arg_event="$1" ;;        # codex native event name
esac
[ -n "$payload" ] || payload=$(cat 2>/dev/null || printf '')

EVENT_TYPE="${CLAUDE_HOOK_EVENT_TYPE:-}"
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
USER_MSG=""
GOAL=""

if command -v python3 >/dev/null 2>&1; then
  parsed=$(printf '%s' "$payload" | python3 -c '
import base64, json, sys
from pathlib import Path

raw = sys.stdin.read()

def oneline(text, limit=600):
    return " ".join(str(text).split())[:limit]

def msg_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        out = []
        for it in content:
            if isinstance(it, dict) and isinstance(it.get("text"), str):
                out.append(it["text"])
        return "\n".join(out)
    return ""

# Normalize one transcript line (codex payload-wrapped or claude/grok flat) to
# (role, text, turn_id).
def normalize(item):
    if not isinstance(item, dict):
        return None
    inner = item.get("payload") if isinstance(item.get("payload"), dict) else None
    src = inner or (item.get("message") if isinstance(item.get("message"), dict) else item)
    if not isinstance(src, dict):
        return None
    if inner is not None and src.get("type") not in (None, "message"):
        return None
    role = src.get("role") or item.get("role")
    text = msg_text(src.get("content"))
    if not text:
        return None
    turn = None
    meta = (inner or {}).get("metadata")
    if isinstance(meta, dict):
        turn = meta.get("turn_id")
    return (role, text, turn)

def scan_transcript(path, want_turn):
    last_user = ""
    last_assistant = ""
    try:
        with Path(path).open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    item = json.loads(line)
                except Exception:
                    continue
                norm = normalize(item)
                if not norm:
                    continue
                role, text, turn = norm
                if want_turn and turn is not None and turn != want_turn:
                    continue
                if role == "user":
                    last_user = text
                elif role == "assistant":
                    last_assistant = text
    except Exception:
        return "", ""
    return last_user, last_assistant

def gauged_goal(assistant):
    # The agent restates intent as "Your ask: <paraphrase>" (AGENTS.md). That
    # line IS the LLM-gauged latest goal for the turn — scrape the last one.
    found = ""
    for line in assistant.splitlines():
        s = line.strip()
        if s.lower().startswith("your ask:"):
            found = oneline(s.split(":", 1)[1])
    return found

def keep_lines(text, n=3, limit=300):
    lines = []
    for line in str(text).split("\n"):
        if len(lines) >= n:
            break
        lines.append(line[:limit])
    out = "\n".join(lines)
    if len(str(text).split("\n")) > n:
        out += "\n…"
    return out

event = ""; tool = ""; notify_type = ""; user_msg = ""; goal = ""
try:
    d = json.loads(raw) if raw.strip() else {}
    if isinstance(d, dict):
        event = d.get("hook_event_name") or d.get("hookEventName") or ""
        tool = d.get("tool_name") or d.get("toolName") or ""
        notify_type = d.get("type") or ""
        # Direct fields first (claude/grok give the prompt on UserPromptSubmit).
        for key in ("arcmux_last_message", "prompt", "message", "text"):
            v = d.get(key)
            if isinstance(v, str) and v.strip():
                user_msg = v
                break
        goal = ""
        for key in ("arcmux_goal", "goal", "objective"):
            v = d.get(key)
            if isinstance(v, str) and v.strip():
                goal = oneline(v)
                break
        transcript = d.get("transcript_path")
        if isinstance(transcript, str) and transcript:
            turn_id = d.get("turn_id") if isinstance(d.get("turn_id"), str) else None
            t_user, t_assistant = scan_transcript(transcript, turn_id)
            if not user_msg and t_user:
                user_msg = t_user
            if not goal and t_assistant:
                goal = gauged_goal(t_assistant)
except Exception:
    pass

user_b64 = base64.b64encode(keep_lines(user_msg).encode("utf-8")).decode() if user_msg else ""
print(event)
print(tool)
print(notify_type)
print(user_b64)
print(goal)
' 2>/dev/null)
  je=$(printf '%s\n' "$parsed" | sed -n '1p')
  jt=$(printf '%s\n' "$parsed" | sed -n '2p')
  jnotify=$(printf '%s\n' "$parsed" | sed -n '3p')
  user_b64=$(printf '%s\n' "$parsed" | sed -n '4p')
  GOAL=$(printf '%s\n' "$parsed" | sed -n '5p')
  if [ -n "$user_b64" ]; then
    USER_MSG=$(printf '%s' "$user_b64" | python3 -c 'import base64,sys;sys.stdout.write(base64.b64decode(sys.stdin.read()).decode("utf-8","replace"))' 2>/dev/null)
  fi
else
  je=$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$je" ] || je=$(printf '%s' "$payload" | sed -n 's/.*"hookEventName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jt=$(printf '%s' "$payload" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  [ -n "$jt" ] || jt=$(printf '%s' "$payload" | sed -n 's/.*"toolName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
  jnotify=$(printf '%s' "$payload" | sed -n 's/.*"type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | sed -n '1p')
fi

# Resolve the native event: codex argv hint, else JSON event, else notify type.
[ -n "$arg_event" ] && EVENT_TYPE="$arg_event"
[ -n "$je" ] && [ -z "$arg_event" ] && EVENT_TYPE="$je"
[ -n "$EVENT_TYPE" ] || EVENT_TYPE="$jnotify"
[ -n "$jt" ] && TOOL_NAME="$jt"
[ -n "$EVENT_TYPE" ] || EVENT_TYPE=unknown

# 1) JSONL audit (only when an output dir was provided).
if [ -n "$ARCMUX_HOOK_OUTPUT_DIR" ]; then
  out="$ARCMUX_HOOK_OUTPUT_DIR/arcmux-hooks-$ARCMUX_SESSION_ID.jsonl"
  mkdir -p "$ARCMUX_HOOK_OUTPUT_DIR" 2>/dev/null
  printf '{"event":"%s","tool":"%s","ts":"%s","session_id":"%s"}\n' \
    "$EVENT_TYPE" "$TOOL_NAME" "$(date -u +%FT%TZ)" "$ARCMUX_SESSION_ID" >> "$out"
fi

# 2) Map the native event (claude PascalCase, grok snake_case, codex names) to a
# canonical event. Unmapped events are dropped (exit 0), not recorded as noise.
case "$EVENT_TYPE" in
  UserPromptSubmit|user_prompt_submit)            CANON=prompt_submit; TOOL_NAME="" ;;
  PreToolUse|pre_tool_use)                         CANON=tool_start ;;
  PostToolUse|post_tool_use)                       CANON=tool_end ;;
  Stop|stop|SubagentStop|agent-turn-complete)      CANON=turn_end; TOOL_NAME="" ;;
  Notification|notification|approval-requested|PermissionRequest) CANON=notification ;;
  SessionStart|SubagentStart|PreCompact|PostCompact)              CANON=notification ;;
  unknown)                                         CANON=notification ;;
  *)                                               exit 0 ;;
esac

# 3) Mutate the exact session-id-keyed state doc. arcmux hook reads
# session/agent/state-dir from env by
# default; pass recording fields only when present so empty values never clobber.
ARCMUX_BIN="${ARCMUX_BIN:-arcmux}"
set -- hook --agent "${ARCMUX_HOOK_AGENT:-claude}" --event "$CANON" --tool "$TOOL_NAME"
[ -n "$GOAL" ] && set -- "$@" --goal "$GOAL"
[ -n "$USER_MSG" ] && set -- "$@" --last-message "$USER_MSG"
if [ -n "$GOAL$USER_MSG" ]; then
  set -- "$@" --contract-source "$EVENT_TYPE"
fi
"$ARCMUX_BIN" "$@" >/dev/null 2>&1 || true

exit 0
