// Package bootstrap generates the per-launch shell script that cmux (or any
// other launcher) runs as the workspace's initial command. The script is
// prompt-agnostic: it exports the ARCMUX_* env vars the substrate uses to
// locate per-project state, then `exec`s a caller-supplied command so the
// script's PID is replaced by the agent's process.
//
// arcmux does NOT know what role, prompt, or system message the agent runs
// with. That is the caller's responsibility — elonco (or any other
// orchestrator) constructs the launch command (typically something like
// `claude --append-system-prompt-file /path/to/role.md`) and passes it in.
//
// The script lives at ~/data/arcmux/<project>/<script-name> so it is
// inspectable by the user — no opaque cmux state.
package bootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Options describe one bootstrap script to materialize.
type Options struct {
	// Project is the project slug. Exported as ARCMUX_PROJECT.
	Project string
	// EphemRoot is ~/data/arcmux/<project>/. Exported as ARCMUX_EPHEMERAL.
	EphemRoot string
	// VaultRoot is $OBS_AGENTS. Exported as ARCMUX_VAULT.
	VaultRoot string
	// DataRoot is ~/data. Exported as ARCMUX_DATA.
	DataRoot string
	// Command is the exact shell command to `exec`. The script writes
	// `exec <Command>` verbatim — quote your arguments yourself. arcmux is
	// prompt-agnostic; the caller decides what agent to launch and how.
	Command string
	// Agent is an informational tag exported as ARCMUX_AGENT (e.g. "claude",
	// "codex", "shell"). It does not affect Command. Optional.
	Agent string
	// Env is a map of additional opaque tags to export as ARCMUX_<KEY>.
	// Keys are uppercased and exported in sorted order for stable output.
	// Use this for caller-defined identity tags like ROLE, TEAM, SLOT,
	// CONTRACT — arcmux treats them as strings, not interpretation hints.
	Env map[string]string
	// ScriptName overrides the on-disk filename. Defaults to "bootstrap.sh".
	ScriptName string
}

// Render writes the bootstrap script and returns its absolute path.
// Existing scripts are overwritten so a re-launch picks up command changes.
func Render(opts Options) (string, error) {
	if opts.Project == "" {
		return "", fmt.Errorf("Render: Project required")
	}
	if opts.EphemRoot == "" {
		return "", fmt.Errorf("Render: EphemRoot required")
	}
	if opts.Command == "" {
		return "", fmt.Errorf("Render: Command required")
	}

	body := buildScript(opts)

	if err := os.MkdirAll(opts.EphemRoot, 0o755); err != nil {
		return "", err
	}
	name := opts.ScriptName
	if name == "" {
		name = "bootstrap.sh"
	}
	path := filepath.Join(opts.EphemRoot, name)
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", err
	}
	return path, nil
}

func buildScript(o Options) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by arcmux — safe to inspect, do not hand-edit.\n")
	b.WriteString("# Regenerated by the substrate caller on each launch.\n")
	b.WriteString("set -e\n\n")
	b.WriteString(fmt.Sprintf("export ARCMUX_PROJECT=%s\n", shellQuote(o.Project)))
	if o.Agent != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_AGENT=%s\n", shellQuote(o.Agent)))
	}
	if o.VaultRoot != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_VAULT=%s\n", shellQuote(o.VaultRoot)))
	}
	if o.DataRoot != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_DATA=%s\n", shellQuote(o.DataRoot)))
	}
	b.WriteString(fmt.Sprintf("export ARCMUX_EPHEMERAL=%s\n", shellQuote(o.EphemRoot)))

	// Caller-supplied tags, emitted in sorted order for stable output.
	keys := make([]string, 0, len(o.Env))
	for k := range o.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v := o.Env[k]
		if v == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("export ARCMUX_%s=%s\n", strings.ToUpper(k), shellQuote(v)))
	}

	b.WriteString("\n")
	b.WriteString("exec ")
	b.WriteString(o.Command)
	b.WriteString("\n")
	return b.String()
}

// shellQuote single-quotes a string for safe inclusion in a bash script.
func shellQuote(s string) string {
	// Replace any embedded single quotes with the standard '"'"' dance.
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
