// Package bootstrap generates the per-launch shell script that cmux runs
// as the workspace's initial command. The script primes the agent's
// identity (role file via --append-system-prompt-file), exports the
// ARCMUX_* env vars the agent reads to find its context, and exec's the
// agent so the script's PID is replaced by the agent's process.
//
// The script lives at ~/data/arcmux/<project>/bootstrap-<role>.sh so it is
// inspectable by the user — no opaque cmux state.
package bootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Options describe one bootstrap script to materialize.
type Options struct {
	Agent     string // "claude" | "codex"
	Project   string // slug
	Role      string // "elon" | "manager" | "ic-<role>"
	EphemRoot string // ~/data/arcmux/<project>/
	VaultRoot string // $OBS_AGENTS
	DataRoot  string // ~/data/
	RoleFile  string // absolute path to the role markdown file
	Team      string // team slug, for manager/IC bootstraps (optional)
	Slot      string // slot id, for IC bootstraps only — exports ARCMUX_SLOT (optional)
	Contract  string // initial contract id, for IC bootstraps (optional)
	ScriptName string // override script filename; defaults to bootstrap-<role>.sh
}

// Render writes the bootstrap script and returns its absolute path.
// Existing scripts are overwritten so a re-launch picks up role-file changes.
func Render(opts Options) (string, error) {
	if opts.Agent == "" || opts.Project == "" || opts.Role == "" {
		return "", fmt.Errorf("Render: Agent, Project, Role required")
	}
	if opts.EphemRoot == "" || opts.VaultRoot == "" || opts.RoleFile == "" {
		return "", fmt.Errorf("Render: EphemRoot, VaultRoot, RoleFile required")
	}

	body, err := buildScript(opts)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(opts.EphemRoot, 0o755); err != nil {
		return "", err
	}
	name := opts.ScriptName
	if name == "" {
		name = fmt.Sprintf("bootstrap-%s.sh", opts.Role)
	}
	path := filepath.Join(opts.EphemRoot, name)
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", err
	}
	return path, nil
}

func buildScript(o Options) (string, error) {
	agentCmd, err := agentInvocation(o)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by arcmux manager mode — safe to inspect, do not hand-edit.\n")
	b.WriteString("# Re-running 'arcmux manager <agent> <project>' regenerates this script.\n")
	b.WriteString("set -e\n\n")
	b.WriteString(fmt.Sprintf("export ARCMUX_PROJECT=%s\n", shellQuote(o.Project)))
	b.WriteString(fmt.Sprintf("export ARCMUX_ROLE=%s\n", shellQuote(o.Role)))
	b.WriteString(fmt.Sprintf("export ARCMUX_AGENT=%s\n", shellQuote(o.Agent)))
	b.WriteString(fmt.Sprintf("export ARCMUX_VAULT=%s\n", shellQuote(o.VaultRoot)))
	b.WriteString(fmt.Sprintf("export ARCMUX_DATA=%s\n", shellQuote(o.DataRoot)))
	b.WriteString(fmt.Sprintf("export ARCMUX_EPHEMERAL=%s\n", shellQuote(o.EphemRoot)))
	b.WriteString(fmt.Sprintf("export ARCMUX_ROLE_FILE=%s\n", shellQuote(o.RoleFile)))
	if o.Team != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_TEAM=%s\n", shellQuote(o.Team)))
	}
	if o.Slot != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_SLOT=%s\n", shellQuote(o.Slot)))
	}
	if o.Contract != "" {
		b.WriteString(fmt.Sprintf("export ARCMUX_CONTRACT=%s\n", shellQuote(o.Contract)))
	}
	b.WriteString("\n")
	b.WriteString(agentCmd)
	b.WriteString("\n")
	return b.String(), nil
}

// agentInvocation returns the `exec` line that replaces the script's PID
// with the agent's process.
func agentInvocation(o Options) (string, error) {
	switch o.Agent {
	case "claude":
		// --append-system-prompt-file primes the role identity without
		// stomping Claude's default system prompt (which we want intact for
		// tool-use, hooks, skills, etc).
		// --dangerously-skip-permissions: arcmux-managed agents are trusted
		// (they operate inside the user's sandbox and ARCMUX_* env scope).
		// Skipping trust dialogs is mandatory for unattended dispatch and
		// matches the user's existing tmux-dispatch convention.
		return fmt.Sprintf("exec claude --dangerously-skip-permissions --append-system-prompt-file %s\n",
			shellQuote(o.RoleFile)), nil
	case "codex":
		// codex doesn't expose an --append-system-prompt-file flag today;
		// we use -c to set instructions inline by reading the file via $().
		// This keeps codex bootstrap functional until a cleaner channel ships.
		return fmt.Sprintf("exec codex -c instructions=\"$(cat %s)\"\n",
			shellQuote(o.RoleFile)), nil
	default:
		return "", fmt.Errorf("agentInvocation: unsupported agent %q", o.Agent)
	}
}

// shellQuote single-quotes a string for safe inclusion in a bash script.
func shellQuote(s string) string {
	// Replace any embedded single quotes with the standard '"'"' dance.
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
